dist: bionic
language: elixir
elixir:
- 1.10.3
otp_release:
- 23.0.2
cache:
  directories:
  - _build
  - deps
before_install:
  - sudo apt-get update
  # build utils required to compile github.com/boydm/scenic_driver_glfw
  - sudo apt-get install -y pkgconf libglfw3 libglfw3-dev libglew2.0 libglew-dev
  - mix local.hex --force
  - mix local.rebar --force
  - mix archive.install --force hex nerves_bootstrap
script:
  - mix coveralls.json
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - MIX_ENV=test
