language: elixir
elixir:
- 1.10.3
otp_release:
- 23.0.2
cache:
  directories:
  - _build
  - deps
before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix archive.install --force hex nerves_bootstrap
script:
  - mix do setup, coveralls.json
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - MIX_ENV=test